name: Run tests and publish reports

on:
  workflow_dispatch:
  push:
    branches:
      - main    

jobs:
  test-and-publish-report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17

    - name: Run tests
      run: ./gradlew clean test
        
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: build/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: $
        publish_branch: gh-pages
        publish_dir: allure-history

    - name: Upload Allure Report as an Artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: allure-report
        path: allure-report
